spring.application.name=shiftplanner_server

spring.datasource.url=jdbc:postgresql://localhost:5433/shiftplanner
spring.datasource.username=sp_user
spring.datasource.password=secure_app_password
spring.datasource.driver-class-name=org.postgresql.Driver

